### ISSUE TITLE
Remove quizzes from config

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.starknet.quest#240] opened 2024-08-17 11:48 UTC
The quizzes were managed using the config in the past, but now we use a database to do so.

You can remove:
 - The whole quiz section from the config template (`config.template.toml`)
 - Remove the quizzes fields from the config parser (`src/config.rs`)

**Comment by od-hunter** [comment] 2024-08-22 09:29
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a blockchain developer with vast experience in html, css, react, JavaScript, typescript, solidity and Cairo.

### How I plan on tackling this issue
To solve this issue, I'd simply:
1. Delete the quiz-related section from config.template.toml.
2. Update Config Parser, that is, remove quiz fields and parsing logic from src/config.rs.
3. Lastly, I'll verify changes to ensure no residual quiz-related code or logic remains.

Please assign me so I can work on this ASAP

**Comment by ScottyDavies** [comment] 2024-08-22 09:31
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am front end developer with 6 years experience. 
i have worked with microsoft on several projects,
this will be my first time contributing to the hackathon and i am ready to work


### How I plan on tackling this issue
I would approach this issue with following steps
Remove the quiz section from the config template (config.template.toml):
Locate the config.template.toml file in your project.
Identify the section related to quizzes and remove it completely.
This could involve removing a section like [quizzes] and any associated fields beneath it.
Remove the quizzes fields from the config parser (src/config.rs):
Locate the src/config.rs file in your project.
Identify the struct or module that handles the configuration parsing.
Remove any fields, structs, or functions related to the quizzes from the configuration parser.
This could involve removing properties like quizzes from the main configuration struct, as well as any supporting structures or parsing logic for the quiz-related data.

**Comment by SoarinSkySagar** [comment] 2024-08-22 09:49
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am a blockchain developer with a year of experience and I have experience in using and contributing to repos using Rust. I have developed Rust smart contracts, Rust projects and can definitely tackle this issue. 

### How I plan on tackling this issue
I have checked out the config.template.toml file already for another issue, so I can confidently say that this issue is solvable by me
I will:
1. Remove the whole quiz section from the config template and check if removing them introduces any errors. If it does, will implement ways to make it work while having same functionality but cleaner code
2. Remove all the quizzes fields from config parser
3. Ensure there are no errors introduced by my code
4. Ensure any changes are readable before final PR

**Comment by SoarinSkySagar** [comment] 2024-08-22 09:50
Hi @Marchand-Nicolas , would love to work on this. Please assign

**Comment by LazarusAA** [comment] 2024-08-22 09:53
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm a blockchain developer with experience in rust, JavaScript, typescript, solidity and Cairo. This is my first time contributing to Starknet Quest and Id love to work on this issue.

### How I plan on tackling this issue
- Remove quiz section from config.template.toml
- Remove quizzes fields from src/config.rs

Thank you for your consideration.

**Comment by raizo07** [comment] 2024-08-22 10:22
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello I'll like to be assigned to work on this. ETA: one day.

**Comment by Benjtalkshow** [comment] 2024-08-22 11:00
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I can  work on removing the quizzes from the configuration management. My name is Benjamin, and I have extensive experience in configuration management and refactoring code to adapt to new systems and technologies.

## Understanding the Issue

Previously, quizzes were managed using the config file, but we have now transitioned to using a database for this purpose. To streamline the configuration and remove deprecated elements, the following changes are needed:

1. **Remove the quiz section from the config template.**
2. **Update the config parser to eliminate references to quizzes.**


### How I plan on tackling this issue
### Remove Quiz Section from Config Template

- **Update `config.template.toml`**: I will remove the entire quiz section from the config template file to reflect the current use of the database for managing quizzes.

### Remove Quiz Fields from Config Parser

- **Update `src/config.rs`**: I will remove the quiz-related fields and logic from the config parser to ensure that the application no longer processes or expects quiz data from the config file.

## Benefits

Removing quizzes from the configuration will:

- **Simplify Configuration**: Clean up the config file and remove obsolete sections, making it easier to manage.
- **Align with Current System**: Reflect the current system architecture where quizzes are managed through the database, ensuring consistency and reducing potential sources of errors.

**Comment by bitfalt** [comment] 2024-08-22 11:53
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hii, my name is Daniel and I'm active OSS contributor. I'm also a software and web3 developer. I've done issues with Cairo before which relate to Rust, so I know the language syntax and when a struct is defined properly. I'm also a member of the Dojo Coding community.

### How I plan on tackling this issue
The way I would tackle the issue is in the following way:
- Read both files and identify the quiz section and quizzes fields.
- Once I've seen which parts of the code I need to remove, I'll remove them accordingly
- Compile the program to make sure everything is correct regarding dependencies of the quizzes.
- Run the tests to make sure everything is working properly.
- If any questions come up while I'm working, I will ask one of the maintainers.

**Comment by ShantelPeters** [comment] 2024-08-22 13:39
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I have experience in Rust development, particularly with configuration management and database integration. I can efficiently update the config template and parser by removing outdated quiz sections and ensuring compatibility with the new database-driven approach.

### How I plan on tackling this issue
To address this, I'll:

1. **Update the Config Template**: Remove the quiz section from `config.template.toml` to reflect the transition to database management.
2. **Modify the Config Parser**: Edit `src/config.rs` to eliminate the quiz-related fields, ensuring the parser aligns with the current database setup.

**Comment by EmmanuelAR** [comment] 2024-08-22 15:35
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Heyyy can i work on this? I Emmanuel Software dev from Costa Rica and Dojo Coding

### How I plan on tackling this issue
I will...
1. Remove Quiz Section from the Config Template

	•	Locate the config.template.toml file in your project.
	•	Find the Quiz Section: Search for the [quiz] section or any fields related to quizzes within this file.
	•	Delete the Section: Remove the entire quiz section and any associated fields.

2. Remove Quiz Fields from the Config Parser

	•	Locate the config.rs file in the src directory**.
	•	Identify Quiz-Related Fields: Look for any variables, structs, or functions related to quizzes within this file.
	•	Remove the Quiz-Related Code: Delete any fields, functions, or logic related to parsing quizzes from the config.

3. Test the Changes

	•	Build and Run Tests: After making the changes, rebuild your project and run any existing tests to ensure everything still works as expected.
	•	Check for Errors: Verify that there are no errors related to the config changes.

4. Commit the Changes

	•	Document the Changes: In your commit message, mention that the quiz management has been removed from the config template and parser.
	•	Push the Changes: Once everything is confirmed to be working, push your changes to the repository.

**Closed** 2024-08-24 10:47 UTC
Labels: 🍒 Nice to have, OD Hack 7, Good first issue
