### ISSUE TITLE
Remove unused quests

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.starknet.quest#239] opened 2024-08-17 11:42 UTC
Check on https://starknet.quest/ to see which quests are expired/unused. Remove everything related to these quests, such as verification routes.

**Comment by ScottyDavies** [comment] 2024-08-22 09:34
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am front end developer with 6 years experience. 
i have worked with microsoft on several projects,
this will be my first time contributing to the hackathon and i am ready to work



### How I plan on tackling this issue
I would approach this issue with following steps
Identify expired/unused quests:
Visit the https://starknet.quest/ website and review the "Quests" section to identify any quests that are no longer active or being used.
Remove all references to the expired/unused quests:
Locate the codebase or backend systems that manage the quests on the website.
Remove any code, configuration, or data related to the expired/unused quests, such as:
Removing the quest details from the database or data storage.
Deleting any API routes or endpoints that were used to handle the expired/unused quests.
Removing the quest information from the website's frontend, including any pages, sections, or components related to the quests.
Update the verification routes:
Review the verification routes or processes that were used to validate user participation in the expired/unused quests.
Remove or update these verification routes to ensure that they no longer support the expired/unused quests.
Ensure that any remaining verification processes are still valid and functional for the active quests.
Clean up any leftover assets or resources:
Identify and remove any leftover assets, images, or other resources that were associated with the expired/unused quests.
This may include deleting files, images, or other media from the server or content delivery network (CDN).
Test and validate the changes:
After making the necessary changes, thoroughly test the website and backend systems to ensure that all references to the expired/unused quests have been removed.
Verify that the user experience and any remaining quest-related functionality are not affected by the changes.

**Comment by LazarusAA** [comment] 2024-08-22 10:08
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm a blockchain developer with experience in rust, JavaScript, typescript, solidity and Cairo. This is my first time contributing to Starknet Quest and Id love to work on this issue.

### How I plan on tackling this issue
- Check https://starknet.quest/ to see which quests are expired/unused
- Remove everything related to this quests
- Clean up any leftover assets 
- Ensure everything works as intended before PR

Thank you for your consideration.

**Comment by raizo07** [comment] 2024-08-22 10:23
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hello, I'll love to be assigned to work on this. I'll deliver as soon as possible

**Comment by Benjtalkshow** [comment] 2024-08-22 11:03
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am excited to work on removing unused quests from our system. My name is Benjamin, and I have extensive experience in managing and maintaining backend systems, including removing deprecated or unused features.

## Understanding the Issue

There are quests listed on [Starknet Quest](https://starknet.quest/) that have either expired or are no longer in use. To keep our system clean and efficient, we need to:


### How I plan on tackling this issue
### Identify Unused Quests

- **Check Starknet Quest**: I will review the list of quests on [Starknet Quest](https://starknet.quest/) to identify which quests are expired or no longer in use.

### Remove Related Components

- **Remove Verification Routes**: I will locate and remove any verification routes or other related components in our system that pertain to the unused quests.

**Comment by renzobanegass** [comment] 2024-08-22 12:27
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Hey @Marchand-Nicolas, I'm Renzo, I'm a Software Engineer with over 5 years of experience in the industry, I have worked for a variety of projects like Trivia Crack and Stumble Guys before, I started my journey in Web3 as a member of Dojo Coding last month, participating in the last OD Hack. I'm aiming to maintain consistency in my contributions so I would love to help you with this issue.

### How I plan on tackling this issue
First I would, as suggested, review the quests on the website, then, based on that:
- Take note of all the expired/unused quests
- Identify related code in the repository
- Remove unused code
- Refactor if necessary
- Test everything still works fine
- Remove any related information about those quests in the documentation, if any
- Submit a PR
- Follow up on feedback

Thanks for reading my proposal!

**Comment by EmmanuelAR** [comment] 2024-08-22 15:36
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
Heyyy can i work on this? I Emmanuel Software dev from Costa Rica and Dojo Coding

### How I plan on tackling this issue
1. Identify Expired/Unused Quests

	•	Visit Starknet Quest: Go to https://starknet.quest/ and log in if required.
	•	Check Quest Status: Browse through the quests to identify which ones are expired or no longer in use.

2. Locate Quest-Related Code

	•	Search for Quests in Your Codebase: Identify where the quests are referenced in your project. Common places include:
	•	Verification Routes: Routes that handle verification for these quests.
	•	Quest Configuration/Database Entries: Look for any configuration files, database entries, or hardcoded references to these quests.

3. Remove Unused Quests

	•	Delete Verification Routes: Remove any routes or endpoints in your code that handle verification for the expired or unused quests.
	•	Remove Quest References: Delete any references to these quests in configuration files, database records, or other parts of your codebase.

4. Clean Up Dependencies

	•	Check for Dependencies: Ensure that removing these quests doesn’t affect other parts of your project. Update or refactor code as needed to avoid any broken dependencies.
	•	Test: Run your tests and do a thorough check to ensure nothing is broken after the removal.

5. Document the Cleanup

	•	Document What Was Removed: Keep a record of the quests that were removed and any related changes.
	•	Commit and Push: Commit the changes with a clear message, such as “Removed expired/unused quests and related routes,” and push them to your repository.

**Comment by EmmanuelAR** [comment] 2024-08-22 19:25
Letsss go, thanks for the opportunity, i will start asap @Marchand-Nicolas

**Comment by DIWAKARKASHYAP** [comment] 2024-08-26 16:53
i want to work on this issue

**Closed** 2024-08-28 17:58 UTC
Labels: 🍒 Nice to have, OD Hack 7
