### ISSUE TITLE
Update axum_auto_routes

### ISSUE THREAD

**Issue by Marchand-Nicolas** [starknet-id/api.starknet.quest#236] opened 2024-08-17 11:20 UTC
The aim of this issue is to simplify the way we handle http requests. More specifically, this is the `routing` system we want to improve, using the `axum_auto_routes` library: https://github.com/th0rgal/axum_auto_routes

Currently an outdated version of this lib is used which requires us to specify the path of the function (while instead you can now optionally specify middlewares)

**Comment by ScottyDavies** [comment] 2024-08-22 09:41
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I am front end developer with 6 years experience. 
i have worked with microsoft on several projects,
this will be my first time contributing to the hackathon and i am ready to work


### How I plan on tackling this issue
I would approach this issue with following steps

Set up a global route registry: In your main application, you need to set up a global route registry using a Mutex<Vec<Box<dyn WithState>>>. This registry will store the routes that will be registered with the Axum router.
Implement the WithState trait: You need to implement the WithState trait for your Router type. This trait provides the to_router method to convert the Router into one that is associated with the shared application state.
Use the #[route] macro: Annotate your async route handler functions with the #[route] macro, specifying the HTTP method and the route path. Optionally, you can also specify the module path if the function is not in the root module.
Assemble the final Axum app: In your main function, you can then assemble the final Axum app by iterating over the ROUTE_REGISTRY, merging all the registered routes, and setting up the server.

**Comment by PoulavBhowmick03** [comment] 2024-08-22 12:30
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
I'm Poulav Bhowmick, a software engineer at Invisible Studios with a robust background in TypeScript, Rust, Solidity Cairo, fullstack development and blockchain technology. My experience includes building robust applications, optimizing functionalities and blockchain integration. I have actively participated in events and open source contributions, enhancing my capability to tackle real-world tech challenges. My projects can be viewed on my GitHub Profile and OnlyDust Profile. Plus I´m active member of Starknet community.

### How I plan on tackling this issue
To update and simplify the routing system using the `axum_auto_routes` library, here’s how I would approach the problem:

### 1. **Update the Dependency**
   - **Update `Cargo.toml`:** Replace the outdated version of `axum_auto_routes` with the latest version by adding the following line:
     ```toml
     [dependencies]
     axum_auto_routes = { git = "https://github.com/Th0rgal/axum_auto_routes" }
     axum = "0.5"  # Ensure the axum version matches your project’s requirements
     ctor = "0.1"
     ```
   - **Run `cargo update`:** Update the dependencies to fetch the latest version of the `axum_auto_routes` library.

### 2. **Review Existing Routes**
   - **Identify Outdated Implementations:** Review the current routing logic, especially focusing on the use of outdated paths that require specifying the function path manually.
   - **Replace with `#[route]` Macro:** Convert existing route handler functions to use the `#[route]` macro provided by `axum_auto_routes`. This macro allows you to annotate async functions with HTTP methods and paths, streamlining the route registration process.

### 3. **Refactor Route Registration**
   - **Global Route Registry:** Ensure that the global route registry is set up using `lazy_static!` as shown in the provided example.
   - **Implement `WithState` Trait:** Verify that the `WithState` trait is implemented correctly, allowing your routes to be merged into the Axum router with shared state.
   - **Simplify the Routing Logic:** Refactor the routing logic in `main.rs` to utilize the global route registry. This will involve folding over the registered routes and merging them into the main router.

### 4. **Add Middleware (Optional)**
   - **Integrate Middleware:** With the new version, you can optionally specify middlewares directly in the route definitions. If needed, define middleware layers and integrate them with specific routes or globally.

### 5. **Test and Validate**
   - **Run Unit Tests:** Ensure all existing unit tests pass with the new routing system. Update or add new tests if necessary.
   - **Manual Testing:** Perform manual testing by running the application and verifying that the routes are correctly registered and accessible as expected.
   - **Check Middleware Functionality:** If you’ve added middleware, verify that it works as intended.

### 6. **Documentation and Cleanup**
   - **Document Changes:** Update any relevant documentation to reflect the new routing approach using `axum_auto_routes`.
   - **Code Cleanup:** Remove any legacy code or unnecessary comments that are no longer relevant after the update.

### 7. **Deployment**
   - **Deploy to Staging:** If your project uses a staging environment, deploy the changes to ensure everything works as expected in a production-like setting.
   - **Monitor Production Deployment:** Once satisfied with staging, deploy to production, monitoring logs and performance to ensure a smooth transition.

This approach ensures a clean, maintainable routing system using the latest features of the `axum_auto_routes` library, making your codebase more robust and easier to manage.

# ETA- 2 days

**Comment by ShantelPeters** [comment] 2024-08-22 13:31
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/starknet-quest).

### My background and how it can be leveraged
With a background in frontend and blockchain development, I've worked extensively with web technologies and libraries. I can leverage my experience to update the routing system by integrating the latest `axum_auto_routes` library, ensuring efficient handling of HTTP requests and improved code maintainability.

### How I plan on tackling this issue
I would update the routing system by upgrading to the latest version of `axum_auto_routes`. This involves:

1. **Installing the Latest Version:** Update dependencies to use the new library version with improved middleware options.
2. **Refactoring Code:** Modify existing routes to leverage optional middleware configurations, simplifying function path specifications.
3. **Testing:** Ensure all routes work as expected with the new setup, verifying compatibility and performance improvements.

**Comment by PoulavBhowmick03** [comment] 2024-08-22 18:05
Thanks! Will start working on it asap

**Closed** 2024-08-25 12:11 UTC
Labels: 🍒 Nice to have, OD Hack 7
